package Vistas.Administrador;

import Modelos.Usuario;
import Servicios.Conexion;
import Servicios.OperacionesUsuario;
import Vistas.Alumno.MenuAlumno;
import Vistas.IniciarSesion;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

public class MenuAdmin extends javax.swing.JFrame {
    private Usuario usuario;
    private Conexion conexion;
    private OperacionesUsuario operaciones;
    public MenuAdmin() {
        initComponents();
    }

    public MenuAdmin(Conexion conexion,Usuario usuario) {
        initComponents();
        String nombre=usuario.getNombre();
        jLabel5.setText(nombre);
        this.usuario=usuario;
        this.conexion=conexion;
        this.operaciones=new OperacionesUsuario(this.conexion);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Imagen = new javax.swing.JPanel();
        jButtonCerrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Contenido = new javax.swing.JPanel();
        Cerrar = new javax.swing.JLabel();
        Minimizar = new javax.swing.JLabel();
        Aprende = new javax.swing.JLabel();
        Practica = new javax.swing.JLabel();
        Administra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");
        setUndecorated(true);

        Imagen.setMaximumSize(new java.awt.Dimension(470, 540));
        Imagen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCerrar.setBackground(new java.awt.Color(0, 51, 204));
        jButtonCerrar.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jButtonCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCerrar.setText("Cerrar sesión");
        jButtonCerrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCerrar.setDefaultCapable(false);
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        Imagen.add(jButtonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 240, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bienvenid@");
        Imagen.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Aqui va el nombre del usuario");
        Imagen.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 470, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Fondo Bateria.jpg"))); // NOI18N
        jLabel3.setText("Aqui va el nombre del usuario");
        Imagen.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 540));

        Contenido.setBackground(new java.awt.Color(255, 255, 255));

        Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_Multiply_32px.png"))); // NOI18N
        Cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarMouseClicked(evt);
            }
        });

        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_Expand_Arrow_32px.png"))); // NOI18N
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
        });

        Aprende.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        Aprende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Aprende.png"))); // NOI18N
        Aprende.setText("Aprende");
        Aprende.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AprendeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AprendeMouseExited(evt);
            }
        });

        Practica.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        Practica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Practica.png"))); // NOI18N
        Practica.setText("Practica");
        Practica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PracticaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PracticaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PracticaMouseExited(evt);
            }
        });

        Administra.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        Administra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Administra.png"))); // NOI18N
        Administra.setText("Administra");
        Administra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdministraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdministraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdministraMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Practica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenidoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Minimizar)
                        .addGap(8, 8, 8)
                        .addComponent(Cerrar))
                    .addComponent(Administra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Aprende, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Minimizar)
                    .addComponent(Cerrar))
                .addGap(18, 18, 18)
                .addComponent(Aprende, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Practica, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Administra, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizarMouseClicked

    private void CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseClicked
        // TODO add your handling code here:
        int opcion=JOptionPane.showConfirmDialog(null, "¿Está seguro que desea salir?","Salir",JOptionPane.YES_NO_OPTION);
        if(opcion==JOptionPane.YES_OPTION){
            System.exit(0);
        }

    }//GEN-LAST:event_CerrarMouseClicked

    private void PracticaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PracticaMouseEntered
        // TODO add your handling code here:
        Practica.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    }//GEN-LAST:event_PracticaMouseEntered

    private void PracticaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PracticaMouseExited
        // TODO add your handling code here:
        Practica.setBorder(null);
    }//GEN-LAST:event_PracticaMouseExited

    private void AprendeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AprendeMouseEntered
        // TODO add your handling code here:
        Aprende.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    }//GEN-LAST:event_AprendeMouseEntered

    private void AprendeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AprendeMouseExited
        // TODO add your handling code here:
        Aprende.setBorder(null);
    }//GEN-LAST:event_AprendeMouseExited

    private void AdministraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdministraMouseEntered
        // TODO add your handling code here:
        Administra.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    }//GEN-LAST:event_AdministraMouseEntered

    private void AdministraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdministraMouseExited
        // TODO add your handling code here:
        Administra.setBorder(null);
    }//GEN-LAST:event_AdministraMouseExited

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            operaciones.CerrarSesion(usuario);
            IniciarSesion vista=new IniciarSesion(conexion,null);
            dispose();
            vista.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAlumno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void AdministraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdministraMouseClicked
        // TODO add your handling code here:
        Administrar vista=new Administrar(conexion,usuario);
        dispose();
        vista.setVisible(true);
    }//GEN-LAST:event_AdministraMouseClicked

    private void PracticaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PracticaMouseClicked
        // TODO add your handling code here:
        PracticarAdmin vista;
        try {
            vista = new PracticarAdmin(conexion,usuario);
            dispose();
            vista.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PracticaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Administra;
    private javax.swing.JLabel Aprende;
    private javax.swing.JLabel Cerrar;
    private javax.swing.JPanel Contenido;
    private javax.swing.JPanel Imagen;
    private javax.swing.JLabel Minimizar;
    private javax.swing.JLabel Practica;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
